# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stream_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stream_gui(object):
    def setupUi(self, stream_gui):
        stream_gui.setObjectName("stream_gui")
        stream_gui.setEnabled(True)
        stream_gui.resize(1200, 735)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stream_gui.sizePolicy().hasHeightForWidth())
        stream_gui.setSizePolicy(sizePolicy)
        stream_gui.setMaximumSize(QtCore.QSize(1200, 735))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 160, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 65, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 87, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 121, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 192, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 160, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 65, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 87, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 121, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 192, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 65, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 160, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 65, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 87, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 65, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 65, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 130, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        stream_gui.setPalette(palette)
        stream_gui.setMouseTracking(False)
        stream_gui.setFocusPolicy(QtCore.Qt.ClickFocus)
        stream_gui.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        stream_gui.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/golden-array-svg.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        stream_gui.setWindowIcon(icon)
        stream_gui.setAutoFillBackground(True)
        self.label_1 = QtWidgets.QLabel(stream_gui)
        self.label_1.setGeometry(QtCore.QRect(410, 20, 581, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_logo = QtWidgets.QLabel(stream_gui)
        self.label_logo.setGeometry(QtCore.QRect(70, 30, 241, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/pic/jlsemi-logo-en-big.png"))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.close_main_win = QtWidgets.QPushButton(stream_gui)
        self.close_main_win.setGeometry(QtCore.QRect(1162, 0, 36, 30))
        self.close_main_win.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/ic_close_white_36dp.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.close_main_win.setIcon(icon1)
        self.close_main_win.setIconSize(QtCore.QSize(24, 24))
        self.close_main_win.setFlat(True)
        self.close_main_win.setObjectName("close_main_win")
        self.minimize_main_win = QtWidgets.QPushButton(stream_gui)
        self.minimize_main_win.setGeometry(QtCore.QRect(1120, 0, 36, 30))
        self.minimize_main_win.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/ic_minimized_white_36dp.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.minimize_main_win.setIcon(icon2)
        self.minimize_main_win.setIconSize(QtCore.QSize(24, 24))
        self.minimize_main_win.setFlat(True)
        self.minimize_main_win.setObjectName("minimize_main_win")
        self.tabWidget = QtWidgets.QTabWidget(stream_gui)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(390, 90, 791, 521))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.stream = QtWidgets.QWidget()
        self.stream.setObjectName("stream")
        self.groupBox = QtWidgets.QGroupBox(self.stream)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 361, 451))
        self.groupBox.setObjectName("groupBox")
        self.tx_group = QtWidgets.QGroupBox(self.groupBox)
        self.tx_group.setGeometry(QtCore.QRect(10, 60, 341, 251))
        self.tx_group.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_group.setObjectName("tx_group")
        self.line = QtWidgets.QFrame(self.tx_group)
        self.line.setGeometry(QtCore.QRect(20, 30, 311, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tx_group)
        self.line_2.setGeometry(QtCore.QRect(20, 110, 311, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tx_group)
        self.line_3.setGeometry(QtCore.QRect(10, 40, 21, 191))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tx_group)
        self.line_4.setGeometry(QtCore.QRect(320, 40, 21, 191))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_3 = QtWidgets.QLabel(self.tx_group)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 131, 31))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tx_group)
        self.label.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.label.setObjectName("label")
        self.tx_pkt_cnt = QtWidgets.QLineEdit(self.tx_group)
        self.tx_pkt_cnt.setGeometry(QtCore.QRect(150, 80, 161, 31))
        self.tx_pkt_cnt.setReadOnly(True)
        self.tx_pkt_cnt.setObjectName("tx_pkt_cnt")
        self.label_5 = QtWidgets.QLabel(self.tx_group)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 121, 31))
        self.label_5.setObjectName("label_5")
        self.line_9 = QtWidgets.QFrame(self.tx_group)
        self.line_9.setGeometry(QtCore.QRect(20, 220, 311, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.tx_end_time = QtWidgets.QLineEdit(self.tx_group)
        self.tx_end_time.setGeometry(QtCore.QRect(150, 190, 161, 31))
        self.tx_end_time.setReadOnly(True)
        self.tx_end_time.setObjectName("tx_end_time")
        self.label_4 = QtWidgets.QLabel(self.tx_group)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 121, 31))
        self.label_4.setObjectName("label_4")
        self.tx_start_time = QtWidgets.QLineEdit(self.tx_group)
        self.tx_start_time.setGeometry(QtCore.QRect(150, 140, 161, 31))
        self.tx_start_time.setReadOnly(True)
        self.tx_start_time.setObjectName("tx_start_time")
        self.tx_end_time.raise_()
        self.label_4.raise_()
        self.tx_start_time.raise_()
        self.label.raise_()
        self.tx_pkt_cnt.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.line_9.raise_()
        self.rx_group = QtWidgets.QGroupBox(self.groupBox)
        self.rx_group.setGeometry(QtCore.QRect(10, 310, 341, 131))
        self.rx_group.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_group.setFlat(False)
        self.rx_group.setObjectName("rx_group")
        self.line_5 = QtWidgets.QFrame(self.rx_group)
        self.line_5.setGeometry(QtCore.QRect(20, 20, 311, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.rx_group)
        self.line_6.setGeometry(QtCore.QRect(20, 110, 311, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.rx_group)
        self.line_7.setGeometry(QtCore.QRect(10, 30, 21, 91))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.rx_group)
        self.line_8.setGeometry(QtCore.QRect(320, 30, 21, 91))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.rx_pkt_cnt = QtWidgets.QLineEdit(self.rx_group)
        self.rx_pkt_cnt.setGeometry(QtCore.QRect(150, 40, 161, 31))
        self.rx_pkt_cnt.setReadOnly(True)
        self.rx_pkt_cnt.setObjectName("rx_pkt_cnt")
        self.label_8 = QtWidgets.QLabel(self.rx_group)
        self.label_8.setGeometry(QtCore.QRect(30, 40, 121, 31))
        self.label_8.setObjectName("label_8")
        self.rx_crc_cnt = QtWidgets.QLineEdit(self.rx_group)
        self.rx_crc_cnt.setGeometry(QtCore.QRect(150, 80, 161, 31))
        self.rx_crc_cnt.setReadOnly(True)
        self.rx_crc_cnt.setObjectName("rx_crc_cnt")
        self.label_17 = QtWidgets.QLabel(self.rx_group)
        self.label_17.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.label_17.setObjectName("label_17")
        self.Stop = QtWidgets.QPushButton(self.groupBox)
        self.Stop.setGeometry(QtCore.QRect(160, 20, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop.sizePolicy().hasHeightForWidth())
        self.Stop.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Stop.setPalette(palette)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/ic_pause_circle_outline_white_36dp.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.Stop.setIcon(icon3)
        self.Stop.setIconSize(QtCore.QSize(36, 36))
        self.Stop.setCheckable(False)
        self.Stop.setChecked(False)
        self.Stop.setAutoExclusive(False)
        self.Stop.setAutoDefault(False)
        self.Stop.setDefault(False)
        self.Stop.setFlat(True)
        self.Stop.setObjectName("Stop")
        self.Send = QtWidgets.QPushButton(self.groupBox)
        self.Send.setGeometry(QtCore.QRect(60, 20, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send.sizePolicy().hasHeightForWidth())
        self.Send.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Send.setPalette(palette)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/ic_play_circle_outline_white_36dp.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.Send.setIcon(icon4)
        self.Send.setIconSize(QtCore.QSize(36, 36))
        self.Send.setCheckable(False)
        self.Send.setChecked(False)
        self.Send.setAutoExclusive(False)
        self.Send.setAutoDefault(False)
        self.Send.setDefault(False)
        self.Send.setFlat(True)
        self.Send.setObjectName("Send")
        self.Clear = QtWidgets.QPushButton(self.groupBox)
        self.Clear.setGeometry(QtCore.QRect(260, 20, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear.sizePolicy().hasHeightForWidth())
        self.Clear.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.Clear.setPalette(palette)
        self.Clear.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/ic_delete_white_36dp.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.Clear.setIcon(icon5)
        self.Clear.setIconSize(QtCore.QSize(36, 36))
        self.Clear.setCheckable(False)
        self.Clear.setAutoExclusive(False)
        self.Clear.setAutoDefault(False)
        self.Clear.setFlat(True)
        self.Clear.setObjectName("Clear")
        self.Send_all = QtWidgets.QPushButton(self.stream)
        self.Send_all.setGeometry(QtCore.QRect(270, 0, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_all.sizePolicy().hasHeightForWidth())
        self.Send_all.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Send_all.setPalette(palette)
        self.Send_all.setIcon(icon4)
        self.Send_all.setIconSize(QtCore.QSize(36, 36))
        self.Send_all.setCheckable(False)
        self.Send_all.setChecked(False)
        self.Send_all.setAutoExclusive(False)
        self.Send_all.setAutoDefault(False)
        self.Send_all.setDefault(False)
        self.Send_all.setFlat(True)
        self.Send_all.setObjectName("Send_all")
        self.Clear_all = QtWidgets.QPushButton(self.stream)
        self.Clear_all.setGeometry(QtCore.QRect(470, 0, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear_all.sizePolicy().hasHeightForWidth())
        self.Clear_all.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.Clear_all.setPalette(palette)
        self.Clear_all.setText("")
        self.Clear_all.setIcon(icon5)
        self.Clear_all.setIconSize(QtCore.QSize(36, 36))
        self.Clear_all.setCheckable(False)
        self.Clear_all.setAutoExclusive(False)
        self.Clear_all.setAutoDefault(False)
        self.Clear_all.setFlat(True)
        self.Clear_all.setObjectName("Clear_all")
        self.Stop_all = QtWidgets.QPushButton(self.stream)
        self.Stop_all.setGeometry(QtCore.QRect(370, 0, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop_all.sizePolicy().hasHeightForWidth())
        self.Stop_all.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Stop_all.setPalette(palette)
        self.Stop_all.setIcon(icon3)
        self.Stop_all.setIconSize(QtCore.QSize(36, 36))
        self.Stop_all.setCheckable(False)
        self.Stop_all.setChecked(False)
        self.Stop_all.setAutoExclusive(False)
        self.Stop_all.setAutoDefault(False)
        self.Stop_all.setDefault(False)
        self.Stop_all.setFlat(True)
        self.Stop_all.setObjectName("Stop_all")
        self.groupBox_2 = QtWidgets.QGroupBox(self.stream)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 50, 351, 451))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tx_group_2 = QtWidgets.QGroupBox(self.groupBox_2)
        self.tx_group_2.setGeometry(QtCore.QRect(10, 60, 341, 251))
        self.tx_group_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_group_2.setObjectName("tx_group_2")
        self.line_10 = QtWidgets.QFrame(self.tx_group_2)
        self.line_10.setGeometry(QtCore.QRect(20, 30, 311, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.tx_group_2)
        self.line_11.setGeometry(QtCore.QRect(20, 110, 311, 21))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.tx_group_2)
        self.line_12.setGeometry(QtCore.QRect(10, 40, 21, 191))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tx_group_2)
        self.line_13.setGeometry(QtCore.QRect(320, 40, 21, 191))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_6 = QtWidgets.QLabel(self.tx_group_2)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 131, 31))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.tx_group_2)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.label_2.setObjectName("label_2")
        self.tx_pkt_cnt_2 = QtWidgets.QLineEdit(self.tx_group_2)
        self.tx_pkt_cnt_2.setGeometry(QtCore.QRect(150, 80, 161, 31))
        self.tx_pkt_cnt_2.setReadOnly(True)
        self.tx_pkt_cnt_2.setObjectName("tx_pkt_cnt_2")
        self.label_16 = QtWidgets.QLabel(self.tx_group_2)
        self.label_16.setGeometry(QtCore.QRect(30, 190, 121, 31))
        self.label_16.setObjectName("label_16")
        self.line_14 = QtWidgets.QFrame(self.tx_group_2)
        self.line_14.setGeometry(QtCore.QRect(20, 220, 311, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.tx_end_time_2 = QtWidgets.QLineEdit(self.tx_group_2)
        self.tx_end_time_2.setGeometry(QtCore.QRect(150, 190, 161, 31))
        self.tx_end_time_2.setReadOnly(True)
        self.tx_end_time_2.setObjectName("tx_end_time_2")
        self.label_18 = QtWidgets.QLabel(self.tx_group_2)
        self.label_18.setGeometry(QtCore.QRect(30, 140, 121, 31))
        self.label_18.setObjectName("label_18")
        self.tx_start_time_2 = QtWidgets.QLineEdit(self.tx_group_2)
        self.tx_start_time_2.setGeometry(QtCore.QRect(150, 140, 161, 31))
        self.tx_start_time_2.setReadOnly(True)
        self.tx_start_time_2.setObjectName("tx_start_time_2")
        self.rx_group_2 = QtWidgets.QGroupBox(self.groupBox_2)
        self.rx_group_2.setGeometry(QtCore.QRect(10, 310, 341, 131))
        self.rx_group_2.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_group_2.setFlat(False)
        self.rx_group_2.setObjectName("rx_group_2")
        self.line_15 = QtWidgets.QFrame(self.rx_group_2)
        self.line_15.setGeometry(QtCore.QRect(20, 20, 311, 21))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.rx_group_2)
        self.line_16.setGeometry(QtCore.QRect(20, 110, 311, 21))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.rx_group_2)
        self.line_17.setGeometry(QtCore.QRect(10, 30, 21, 91))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.rx_group_2)
        self.line_18.setGeometry(QtCore.QRect(320, 30, 21, 91))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.rx_pkt_cnt_2 = QtWidgets.QLineEdit(self.rx_group_2)
        self.rx_pkt_cnt_2.setGeometry(QtCore.QRect(150, 40, 161, 31))
        self.rx_pkt_cnt_2.setReadOnly(True)
        self.rx_pkt_cnt_2.setObjectName("rx_pkt_cnt_2")
        self.label_19 = QtWidgets.QLabel(self.rx_group_2)
        self.label_19.setGeometry(QtCore.QRect(30, 40, 121, 31))
        self.label_19.setObjectName("label_19")
        self.rx_crc_cnt_2 = QtWidgets.QLineEdit(self.rx_group_2)
        self.rx_crc_cnt_2.setGeometry(QtCore.QRect(150, 80, 161, 31))
        self.rx_crc_cnt_2.setReadOnly(True)
        self.rx_crc_cnt_2.setObjectName("rx_crc_cnt_2")
        self.label_20 = QtWidgets.QLabel(self.rx_group_2)
        self.label_20.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.label_20.setObjectName("label_20")
        self.Stop_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Stop_2.setGeometry(QtCore.QRect(160, 20, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop_2.sizePolicy().hasHeightForWidth())
        self.Stop_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Stop_2.setPalette(palette)
        self.Stop_2.setIcon(icon3)
        self.Stop_2.setIconSize(QtCore.QSize(36, 36))
        self.Stop_2.setCheckable(False)
        self.Stop_2.setChecked(False)
        self.Stop_2.setAutoExclusive(False)
        self.Stop_2.setAutoDefault(False)
        self.Stop_2.setDefault(False)
        self.Stop_2.setFlat(True)
        self.Stop_2.setObjectName("Stop_2")
        self.Send_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Send_2.setGeometry(QtCore.QRect(60, 20, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_2.sizePolicy().hasHeightForWidth())
        self.Send_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Send_2.setPalette(palette)
        self.Send_2.setIcon(icon4)
        self.Send_2.setIconSize(QtCore.QSize(36, 36))
        self.Send_2.setCheckable(False)
        self.Send_2.setChecked(False)
        self.Send_2.setAutoExclusive(False)
        self.Send_2.setAutoDefault(False)
        self.Send_2.setDefault(False)
        self.Send_2.setFlat(True)
        self.Send_2.setObjectName("Send_2")
        self.Clear_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Clear_2.setGeometry(QtCore.QRect(260, 20, 48, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear_2.sizePolicy().hasHeightForWidth())
        self.Clear_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.Clear_2.setPalette(palette)
        self.Clear_2.setText("")
        self.Clear_2.setIcon(icon5)
        self.Clear_2.setIconSize(QtCore.QSize(36, 36))
        self.Clear_2.setCheckable(False)
        self.Clear_2.setAutoExclusive(False)
        self.Clear_2.setAutoDefault(False)
        self.Clear_2.setFlat(True)
        self.Clear_2.setObjectName("Clear_2")
        self.line_42 = QtWidgets.QFrame(self.stream)
        self.line_42.setGeometry(QtCore.QRect(380, 50, 21, 461))
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.line_43 = QtWidgets.QFrame(self.stream)
        self.line_43.setGeometry(QtCore.QRect(10, 500, 761, 20))
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.line_44 = QtWidgets.QFrame(self.stream)
        self.line_44.setGeometry(QtCore.QRect(760, 40, 21, 461))
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.line_45 = QtWidgets.QFrame(self.stream)
        self.line_45.setGeometry(QtCore.QRect(10, 40, 761, 20))
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.line_46 = QtWidgets.QFrame(self.stream)
        self.line_46.setGeometry(QtCore.QRect(1, 50, 20, 461))
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.tabWidget.addTab(self.stream, "")
        self.groupBox_5 = QtWidgets.QGroupBox(stream_gui)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 110, 301, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.btnConnect = QtWidgets.QPushButton(self.groupBox_5)
        self.btnConnect.setGeometry(QtCore.QRect(20, 30, 261, 41))
        self.btnConnect.setObjectName("btnConnect")
        self.groupBox_6 = QtWidgets.QGroupBox(stream_gui)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 210, 351, 511))
        self.groupBox_6.setObjectName("groupBox_6")
        self.control_group = QtWidgets.QGroupBox(self.groupBox_6)
        self.control_group.setGeometry(QtCore.QRect(10, 30, 331, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_group.sizePolicy().hasHeightForWidth())
        self.control_group.setSizePolicy(sizePolicy)
        self.control_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.control_group.setFlat(False)
        self.control_group.setCheckable(False)
        self.control_group.setObjectName("control_group")
        self.label_11 = QtWidgets.QLabel(self.control_group)
        self.label_11.setGeometry(QtCore.QRect(170, 40, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.type_combo = QtWidgets.QComboBox(self.control_group)
        self.type_combo.setGeometry(QtCore.QRect(170, 70, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_combo.sizePolicy().hasHeightForWidth())
        self.type_combo.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.type_combo.setPalette(palette)
        self.type_combo.setStyleSheet("color: rgb(206, 92, 0);\n"
"selection-background-color: rgb(19, 41, 61);\n"
"background-color: rgba(243, 243, 243, 240);")
        self.type_combo.setEditable(False)
        self.type_combo.setMaxCount(4)
        self.type_combo.setDuplicatesEnabled(False)
        self.type_combo.setObjectName("type_combo")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.label_9 = QtWidgets.QLabel(self.control_group)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.length_combo = QtWidgets.QComboBox(self.control_group)
        self.length_combo.setGeometry(QtCore.QRect(10, 150, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_combo.sizePolicy().hasHeightForWidth())
        self.length_combo.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.length_combo.setPalette(palette)
        self.length_combo.setStyleSheet("color: rgb(206, 92, 0);\n"
"selection-background-color: rgb(19, 41, 61);\n"
"background-color: rgba(243, 243, 243, 240);")
        self.length_combo.setEditable(False)
        self.length_combo.setMaxCount(4)
        self.length_combo.setDuplicatesEnabled(False)
        self.length_combo.setObjectName("length_combo")
        self.length_combo.addItem("")
        self.length_combo.addItem("")
        self.label_13 = QtWidgets.QLabel(self.control_group)
        self.label_13.setGeometry(QtCore.QRect(170, 120, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.send_combo = QtWidgets.QComboBox(self.control_group)
        self.send_combo.setGeometry(QtCore.QRect(170, 150, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_combo.sizePolicy().hasHeightForWidth())
        self.send_combo.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.send_combo.setPalette(palette)
        self.send_combo.setStyleSheet("color: rgb(206, 92, 0);\n"
"selection-background-color: rgb(19, 41, 61);\n"
"background-color: rgba(243, 243, 243, 240);")
        self.send_combo.setEditable(False)
        self.send_combo.setMaxCount(4)
        self.send_combo.setDuplicatesEnabled(False)
        self.send_combo.setObjectName("send_combo")
        self.send_combo.addItem("")
        self.send_combo.addItem("")
        self.label_7 = QtWidgets.QLabel(self.control_group)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.payload_combo = QtWidgets.QComboBox(self.control_group)
        self.payload_combo.setGeometry(QtCore.QRect(10, 70, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payload_combo.sizePolicy().hasHeightForWidth())
        self.payload_combo.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 41, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.payload_combo.setPalette(palette)
        self.payload_combo.setAcceptDrops(False)
        self.payload_combo.setStyleSheet("color: rgb(206, 92, 0);\n"
"selection-background-color: rgb(19, 41, 61);\n"
"background-color: rgba(243, 243, 243, 240);")
        self.payload_combo.setEditable(False)
        self.payload_combo.setMaxCount(4)
        self.payload_combo.setDuplicatesEnabled(False)
        self.payload_combo.setObjectName("payload_combo")
        self.payload_combo.addItem("")
        self.payload_combo.addItem("")
        self.payload_combo.addItem("")
        self.payload_combo.addItem("")
        self.config_group = QtWidgets.QGroupBox(self.groupBox_6)
        self.config_group.setGeometry(QtCore.QRect(10, 240, 331, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_group.sizePolicy().hasHeightForWidth())
        self.config_group.setSizePolicy(sizePolicy)
        self.config_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.config_group.setObjectName("config_group")
        self.label_15 = QtWidgets.QLabel(self.config_group)
        self.label_15.setGeometry(QtCore.QRect(10, 120, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.pkt_num = QtWidgets.QLineEdit(self.config_group)
        self.pkt_num.setGeometry(QtCore.QRect(10, 150, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkt_num.sizePolicy().hasHeightForWidth())
        self.pkt_num.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 116, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 116, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.pkt_num.setPalette(palette)
        self.pkt_num.setMaxLength(10)
        self.pkt_num.setObjectName("pkt_num")
        self.label_10 = QtWidgets.QLabel(self.config_group)
        self.label_10.setGeometry(QtCore.QRect(200, 40, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.IPG1 = QtWidgets.QLineEdit(self.config_group)
        self.IPG1.setGeometry(QtCore.QRect(200, 70, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IPG1.sizePolicy().hasHeightForWidth())
        self.IPG1.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.IPG1.setPalette(palette)
        self.IPG1.setMaxLength(3)
        self.IPG1.setCursorPosition(3)
        self.IPG1.setObjectName("IPG1")
        self.label_12 = QtWidgets.QLabel(self.config_group)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.payload_val = QtWidgets.QLineEdit(self.config_group)
        self.payload_val.setEnabled(True)
        self.payload_val.setGeometry(QtCore.QRect(10, 70, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payload_val.sizePolicy().hasHeightForWidth())
        self.payload_val.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.payload_val.setPalette(palette)
        self.payload_val.setMaxLength(2)
        self.payload_val.setObjectName("payload_val")
        self.label_14 = QtWidgets.QLabel(self.config_group)
        self.label_14.setGeometry(QtCore.QRect(110, 40, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.length_val = QtWidgets.QLineEdit(self.config_group)
        self.length_val.setGeometry(QtCore.QRect(110, 70, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_val.sizePolicy().hasHeightForWidth())
        self.length_val.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.length_val.setPalette(palette)
        self.length_val.setMaxLength(4)
        self.length_val.setObjectName("length_val")
        self.IPG2 = QtWidgets.QLineEdit(self.config_group)
        self.IPG2.setGeometry(QtCore.QRect(200, 150, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IPG2.sizePolicy().hasHeightForWidth())
        self.IPG2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.IPG2.setPalette(palette)
        self.IPG2.setMaxLength(3)
        self.IPG2.setObjectName("IPG2")
        self.label_22 = QtWidgets.QLabel(self.config_group)
        self.label_22.setGeometry(QtCore.QRect(200, 120, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.config_group)
        self.label_23.setGeometry(QtCore.QRect(280, 70, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.config_group)
        self.label_24.setGeometry(QtCore.QRect(280, 150, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.btnSetConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnSetConfig.setGeometry(QtCore.QRect(20, 450, 301, 41))
        self.btnSetConfig.setObjectName("btnSetConfig")
        self.line_38 = QtWidgets.QFrame(self.groupBox_6)
        self.line_38.setGeometry(QtCore.QRect(0, 220, 351, 21))
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.config_group.raise_()
        self.control_group.raise_()
        self.btnSetConfig.raise_()
        self.line_38.raise_()
        self.line_37 = QtWidgets.QFrame(stream_gui)
        self.line_37.setGeometry(QtCore.QRect(20, 190, 351, 21))
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_39 = QtWidgets.QFrame(stream_gui)
        self.line_39.setGeometry(QtCore.QRect(20, 710, 351, 21))
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.line_40 = QtWidgets.QFrame(stream_gui)
        self.line_40.setGeometry(QtCore.QRect(9, 200, 21, 521))
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.line_41 = QtWidgets.QFrame(stream_gui)
        self.line_41.setGeometry(QtCore.QRect(360, 200, 21, 521))
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.log_info = QtWidgets.QTextEdit(stream_gui)
        self.log_info.setGeometry(QtCore.QRect(390, 640, 791, 81))
        self.log_info.setObjectName("log_info")
        self.label_21 = QtWidgets.QLabel(stream_gui)
        self.label_21.setGeometry(QtCore.QRect(390, 610, 111, 31))
        self.label_21.setObjectName("label_21")
        self.btnClrLog = QtWidgets.QPushButton(stream_gui)
        self.btnClrLog.setGeometry(QtCore.QRect(1060, 610, 121, 31))
        self.btnClrLog.setObjectName("btnClrLog")
        self.groupBox_6.raise_()
        self.tabWidget.raise_()
        self.label_1.raise_()
        self.label_logo.raise_()
        self.close_main_win.raise_()
        self.minimize_main_win.raise_()
        self.groupBox_5.raise_()
        self.line_37.raise_()
        self.line_39.raise_()
        self.line_40.raise_()
        self.line_41.raise_()
        self.log_info.raise_()
        self.label_21.raise_()
        self.btnClrLog.raise_()

        self.retranslateUi(stream_gui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(stream_gui)

    def retranslateUi(self, stream_gui):
        _translate = QtCore.QCoreApplication.translate
        stream_gui.setWindowTitle(_translate("stream_gui", "JLsemi stream"))
        self.label_1.setText(_translate("stream_gui", "Ethernet Stream Generator"))
        self.groupBox.setTitle(_translate("stream_gui", "Phy1"))
        self.tx_group.setTitle(_translate("stream_gui", "Tx Count"))
        self.label_3.setText(_translate("stream_gui", "Send Status"))
        self.label.setText(_translate("stream_gui", "Tx Packet          "))
        self.tx_pkt_cnt.setText(_translate("stream_gui", "0"))
        self.label_5.setText(_translate("stream_gui", "Tx End Time   "))
        self.tx_end_time.setText(_translate("stream_gui", "0"))
        self.label_4.setText(_translate("stream_gui", "Tx Start Time "))
        self.tx_start_time.setText(_translate("stream_gui", "0"))
        self.rx_group.setTitle(_translate("stream_gui", "Rx Count"))
        self.rx_pkt_cnt.setText(_translate("stream_gui", "0"))
        self.label_8.setText(_translate("stream_gui", "Rx Packet          "))
        self.rx_crc_cnt.setText(_translate("stream_gui", "0"))
        self.label_17.setText(_translate("stream_gui", "Rx CRC Err          "))
        self.Stop.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream send</p></body></html>"))
        self.Send.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream send</p></body></html>"))
        self.Clear.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream stop</p></body></html>"))
        self.Send_all.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream send</p></body></html>"))
        self.Clear_all.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream stop</p></body></html>"))
        self.Stop_all.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream send</p></body></html>"))
        self.groupBox_2.setTitle(_translate("stream_gui", "Phy2"))
        self.tx_group_2.setTitle(_translate("stream_gui", "Tx Count"))
        self.label_6.setText(_translate("stream_gui", "Send Status"))
        self.label_2.setText(_translate("stream_gui", "Tx Packet          "))
        self.tx_pkt_cnt_2.setText(_translate("stream_gui", "0"))
        self.label_16.setText(_translate("stream_gui", "Tx End Time   "))
        self.tx_end_time_2.setText(_translate("stream_gui", "0"))
        self.label_18.setText(_translate("stream_gui", "Tx Start Time "))
        self.tx_start_time_2.setText(_translate("stream_gui", "0"))
        self.rx_group_2.setTitle(_translate("stream_gui", "Rx Count"))
        self.rx_pkt_cnt_2.setText(_translate("stream_gui", "0"))
        self.label_19.setText(_translate("stream_gui", "Rx Packet          "))
        self.rx_crc_cnt_2.setText(_translate("stream_gui", "0"))
        self.label_20.setText(_translate("stream_gui", "Rx CRC Err          "))
        self.Stop_2.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream send</p></body></html>"))
        self.Send_2.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream send</p></body></html>"))
        self.Clear_2.setWhatsThis(_translate("stream_gui", "<html><head/><body><p>stream stop</p></body></html>"))
        self.groupBox_5.setTitle(_translate("stream_gui", "MDIO Driver"))
        self.btnConnect.setText(_translate("stream_gui", "Connect"))
        self.groupBox_6.setTitle(_translate("stream_gui", "Stream Set"))
        self.control_group.setTitle(_translate("stream_gui", "Control"))
        self.label_11.setText(_translate("stream_gui", "<html><head/><body><p>Pkt Type</p></body></html>"))
        self.type_combo.setItemText(0, _translate("stream_gui", "100 baset"))
        self.type_combo.setItemText(1, _translate("stream_gui", "10baset"))
        self.label_9.setText(_translate("stream_gui", "<html><head/><body><p>Length Mode</p></body></html>"))
        self.length_combo.setItemText(0, _translate("stream_gui", "random"))
        self.length_combo.setItemText(1, _translate("stream_gui", "fixed"))
        self.label_13.setText(_translate("stream_gui", "<html><head/><body><p>Transmit Mode</p></body></html>"))
        self.send_combo.setItemText(0, _translate("stream_gui", "continuous"))
        self.send_combo.setItemText(1, _translate("stream_gui", "fixed count"))
        self.label_7.setText(_translate("stream_gui", "<html><head/><body><p>PayLoad Mode</p></body></html>"))
        self.payload_combo.setItemText(0, _translate("stream_gui", "random"))
        self.payload_combo.setItemText(1, _translate("stream_gui", "decr (-1)"))
        self.payload_combo.setItemText(2, _translate("stream_gui", "incr (+1)"))
        self.payload_combo.setItemText(3, _translate("stream_gui", "fixed"))
        self.config_group.setTitle(_translate("stream_gui", "Config"))
        self.label_15.setText(_translate("stream_gui", "Count Of Pkts"))
        self.pkt_num.setInputMask(_translate("stream_gui", "9999999999"))
        self.pkt_num.setText(_translate("stream_gui", "10000000"))
        self.label_10.setText(_translate("stream_gui", "<html><head/><body><p>Phy1 Rate</p></body></html>"))
        self.IPG1.setInputMask(_translate("stream_gui", "999"))
        self.IPG1.setText(_translate("stream_gui", "100"))
        self.label_12.setText(_translate("stream_gui", "<html><head/><body><p>Payload</p></body></html>"))
        self.payload_val.setInputMask(_translate("stream_gui", "HH"))
        self.payload_val.setText(_translate("stream_gui", "5a"))
        self.label_14.setText(_translate("stream_gui", "<html><head/><body><p>length</p></body></html>"))
        self.length_val.setInputMask(_translate("stream_gui", "9999"))
        self.length_val.setText(_translate("stream_gui", "64"))
        self.IPG2.setInputMask(_translate("stream_gui", "999"))
        self.IPG2.setText(_translate("stream_gui", "100"))
        self.label_22.setText(_translate("stream_gui", "<html><head/><body><p>Phy2 Rate</p></body></html>"))
        self.label_23.setText(_translate("stream_gui", "<html><head/><body><p>Mbps</p></body></html>"))
        self.label_24.setText(_translate("stream_gui", "<html><head/><body><p>Mbps</p></body></html>"))
        self.btnSetConfig.setText(_translate("stream_gui", "Set Stream Config"))
        self.label_21.setText(_translate("stream_gui", "log info"))
        self.btnClrLog.setText(_translate("stream_gui", "clear log"))

import logo_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    stream_gui = QtWidgets.QWidget()
    ui = Ui_stream_gui()
    ui.setupUi(stream_gui)
    stream_gui.show()
    sys.exit(app.exec_())

